
/*
 * DO NOT EDIT THIS FILE!!! GENERATED AUTOMATICALLY!!!
 *
 * boxy version [boxy 0.1: 01.09.01] based on [RES-RSA 2.9.2: Mar. 13, 2000][GMP]
 */

#include "openssl/bn.h"

void blue_server(unsigned char *out, unsigned char *in);
void blue_server_0(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_server_1(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_server_2(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_server_3(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_server_4(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_client(unsigned char *out, const unsigned char *in);
void blue_client_0(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_client_1(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_client_2(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_client_3(BIGNUM *, BIGNUM *, BIGNUM *);
void blue_client_4(BIGNUM *, BIGNUM *, BIGNUM *);
